In [1]:
import pandas as pd

In [3]:
df = pd.read_csv("../dataset/EPL_2018-2025.csv")
df.head()

,Season,MatchDate,HomeTeam,AwayTeam,FullTimeHomeGoals,FullTimeAwayGoals,FullTimeResult,HalfTimeHomeGoals,HalfTimeAwayGoals,HalfTimeResult,...,HomeShotsOnTarget,AwayShotsOnTarget,HomeCorners,AwayCorners,HomeFouls,AwayFouls,HomeYellowCards,AwayYellowCards,HomeRedCards,AwayRedCards
0,2018/19,2018-08-10,Man United,Leicester,2,1,H,1,0,H,...,6,4,2,5,11,8,2,1,0,0
1,2018/19,2018-08-11,Bournemouth,Cardiff,2,0,H,1,0,H,...,4,1,7,4,11,9,1,1,0,0
2,2018/19,2018-08-11,Fulham,Crystal Palace,0,2,A,0,1,A,...,6,9,5,5,9,11,1,2,0,0
3,2018/19,2018-08-11,Huddersfield,Chelsea,0,3,A,0,2,A,...,1,4,2,5,9,8,2,1,0,0
4,2018/19,2018-08-11,Newcastle,Tottenham,1,2,A,1,2,A,...,2,5,3,5,11,12,2,2,0,0

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2630 entries, 0 to 2629
Data columns (total 22 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Season             2630 non-null   object
 1   MatchDate          2630 non-null   object
 2   HomeTeam           2630 non-null   object
 3   AwayTeam           2630 non-null   object
 4   FullTimeHomeGoals  2630 non-null   int64
 5   FullTimeAwayGoals  2630 non-null   int64
 6   FullTimeResult     2630 non-null   object
 7   HalfTimeHomeGoals  2630 non-null   int64
 8   HalfTimeAwayGoals  2630 non-null   int64
 9   HalfTimeResult     2630 non-null   object
 10  HomeShots          2630 non-null   int64
 11  AwayShots          2630 non-null   int64
 12  HomeShotsOnTarget  2630 non-null   int64
 13  AwayShotsOnTarget  2630 non-null   int64
 14  HomeCorners        2630 non-null   int64
 15  AwayCorners        2630 non-null   int64
 16  HomeFouls          2630 non-null   int64
 17  AwayFouls          2630 non-null   int64
 18  HomeYellowCards    2630 non-null   int64
 19  AwayYellowCards    2630 non-null   int64
 20  HomeRedCards       2630 non-null   int64
 21  AwayRedCards       2630 non-null   int64
dtypes: int64(16), object(6)
memory usage: 452.2+ KB

In [6]:
df.describe()

,FullTimeHomeGoals,FullTimeAwayGoals,HalfTimeHomeGoals,HalfTimeAwayGoals,HomeShots,AwayShots,HomeShotsOnTarget,AwayShotsOnTarget,HomeCorners,AwayCorners,HomeFouls,AwayFouls,HomeYellowCards,AwayYellowCards,HomeRedCards,AwayRedCards
count,2630.000000,2630.000000,2630.000000,2630.000000,2630.000000,2630.000000,2630.000000,2630.000000,2630.000000,2630.000000,2630.000000,2630.000000,2630.000000,2630.000000,2630.000000,2630.000000
mean,1.560456,1.317490,0.712167,0.588593,13.893916,11.606844,4.820152,4.102281,5.693536,4.715209,10.580228,10.799620,1.667681,1.853232,0.055513,0.062738
std,1.332493,1.225427,0.862804,0.793866,5.750664,5.137718,2.624455,2.395117,3.109697,2.812222,3.463694,3.615055,1.278840,1.310830,0.237182,0.250255
min,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000
25%,1.000000,0.000000,0.000000,0.000000,10.000000,8.000000,3.000000,2.000000,3.000000,3.000000,8.000000,8.000000,1.000000,1.000000,0.000000,0.000000
50%,1.000000,1.000000,1.000000,0.000000,13.000000,11.000000,5.000000,4.000000,5.000000,4.000000,10.000000,11.000000,2.000000,2.000000,0.000000,0.000000
75%,2.000000,2.000000,1.000000,1.000000,17.000000,15.000000,6.000000,5.000000,8.000000,6.000000,13.000000,13.000000,2.000000,3.000000,0.000000,0.000000
max,9.000000,9.000000,5.000000,5.000000,36.000000,37.000000,16.000000,15.000000,17.000000,19.000000,23.000000,25.000000,7.000000,8.000000,2.000000,2.000000